### ISSUE TITLE
Email question

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/TS-Languages-Concepts#1]
> In our TS-Languages-Concepts repo, the "my-game-lang" folder is the most befuddling. We've made a "whatdo" folder that contains what appear to be kata card descriptions. It definitely doesn't belong there, but it also doesn't seem to belong inside the Kata-Collections repo. We are unsure of how important the contents of the "whatdo" folder are and whether or not to move or delete them.

**Comment by srfoster** [comment]
It's confusing to me too.  It looks like those files in `whatdo` were intended to be katas somehow.  It may take some work to convert them to katas though.  

If that seems like the way forward, please create new issues for that process.

**Comment by joshalexgibs** [comment]
Removed whatdo due to redundancy / irrelevant nature
